spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hackathon?useSSL=false&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: liushuoyan129
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss